In [26]:
import pandas as pd

df = pd.read_csv('Marion_Fall12.csv')

df

,Frame,Timestamp,Range Min (mmHg),Range Max (mmHg),0,1,2,3,4,5,...,1718,1719,1720,1721,1722,1723,1724,1725,1726,1727
0,1,2024-06-12T13:56:44.812+01:00,0,104,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2,2024-06-12T13:56:44.845+01:00,0,104,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,3,2024-06-12T13:56:44.878+01:00,0,104,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,2024-06-12T13:56:44.91+01:00,0,104,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,5,2024-06-12T13:56:44.942+01:00,0,104,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
209,210,2024-06-12T13:56:51.59+01:00,0,104,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
210,211,2024-06-12T13:56:51.622+01:00,0,104,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
211,212,2024-06-12T13:56:51.655+01:00,0,104,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
212,213,2024-06-12T13:56:51.687+01:00,0,104,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
213,214,2024-06-12T13:56:51.719+01:00,0,104,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [23]:
!dir

 Volume in drive C is OSDisk
 Volume Serial Number is F8D6-0D86

 Directory of C:\Users\Jkb83\Work Folders\Desktop\pressure_mat_camera

26/09/2024  12:32    <DIR>          .
26/09/2024  12:32    <DIR>          ..
15/05/2024  11:31                66 .gitattributes
13/09/2024  12:01             3,269 .gitignore
26/09/2024  09:17    <DIR>          .ipynb_checkpoints
15/05/2024  14:31    <DIR>          data
26/09/2024  08:21           451,142 decision-tree-classifer.ipynb
26/09/2024  08:24            74,191 find_blank_mat_frames.ipynb
16/09/2024  09:08            68,365 find_odd.ipynb
26/09/2024  12:32            10,620 Jonathan_test_26-9.ipynb
15/05/2024  11:31             1,092 LICENSE
15/05/2024  14:21             2,864 make_directories.ipynb
13/09/2024  12:01           393,898 mat_camera_align.ipynb
26/09/2024  08:24           347,305 mat_camera_merge.ipynb
26/09/2024  08:24           158,634 read_mat_camera_data.ipynb
18/06/2024  10:03            34,395 read_timestamps.ipynb
12/08/2024  15:34         5,404,477 rename_as_timestamp.ipynb
17/05/2024  14:31               971 rename_as_timestamp.py
              14 File(s)      6,951,289 bytes
               4 Dir(s)  103,669,792,768 bytes free